services:
  proxy:
    build: velocity/.
    container_name: velocity
    environment:
      TYPE: "VELOCITY"
      VELOCITY_SECRET: "jfei7Ua34jhQ"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - '25565:25565'
    volumes:
      - ./run:/server
      - ./build/libs:/server/plugins/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - islands_network
    secrets:
      - rmq_password
      - rmq_username
      - rmq_host
      - rmq_port
      - redis_password
      - redis_host
      - redis_port
      - redis_username
      - mongodb_password
      - mongodb_username
      - mongodb_host
      - mongodb_port
      - docker_host
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  mongo:
    build: mongodb/.
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_DATABASE: admin
      MONGO_USERNAME_FILE: /run/secrets/mongodb_username
      MONGO_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGO_DATABASE: iswars
    secrets:
      - mongodb_root_password
      - mongodb_root_username
      - mongodb_password
      - mongodb_username
    networks:
      - islands_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/iswars --quiet
      interval: 2s
      timeout: 5s
      retries: 2
      start_period: 5s
    volumes:
      - ./mongodb/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    command: [ --auth ]

  rabbitmq:
    build: rmq/.
    container_name: rmq
    environment:
      RMQ_PASSWORD_FILE: /run/secrets/rmq_password
      RMQ_USERNAME_FILE: /run/secrets/rmq_username
    secrets:
      - rmq_password
      - rmq_username
    networks:
      - islands_network
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 5s

  redis:
    build: redis/.
    container_name: redis
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      REDIS_USERNAME_FILE: /run/secrets/redis_username
      REDIS_DISABLE_DEFAULT_USER: true
    secrets:
      - redis_password
      - redis_username
    networks:
      - islands_network
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -u redis://$(cat /run/secrets/redis_username):$(cat /run/secrets/redis_password)@redis:6379 PING | grep -q PONG" ]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 5s

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - islands_network

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - ./promtail:/etc/promtail
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - islands_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    networks:
      - islands_network

networks:
  islands_network:
    name: islands_dev_network
    driver: bridge

secrets:
  rmq_password:
    file: secrets/rmq_password
  rmq_username:
    file: secrets/rmq_username
  rmq_host:
    file: secrets/rmq_host
  rmq_port:
    file: secrets/rmq_port
  redis_password:
    file: secrets/redis_password
  redis_host:
    file: secrets/redis_host
  redis_port:
    file: secrets/redis_port
  redis_username:
    file: secrets/redis_username
  mongodb_root_password:
    file: secrets/mongodb_root_password
  mongodb_root_username:
    file: secrets/mongodb_root_username
  mongodb_password:
    file: secrets/mongodb_password
  mongodb_username:
    file: secrets/mongodb_username
  mongodb_host:
    file: secrets/mongodb_host
  mongodb_port:
    file: secrets/mongodb_port
  docker_host:
    file: secrets/docker_host
